#include <stdint.h>

const uint16_t colors[] =
{
	0xFFFF, /* A -> White */
	0x0000, /* B -> Black */
	0xF800, /* C -> Red */
	0x04EB, /* D -> Green */
	0xFC00, /* E -> Orange */
	0x9CD3, /* F -> Gray 0 Top */
	0x8430, /* G -> Gray 1 Right */
	0x738E, /* H -> Gray 2 Bottom */
	0xA514, /* I -> Gray 3 */
	0x39E7, /* J -> Gray 4 */
	0x4A49, /* K -> Gray 5 */

	0xFE09, /* L -> Lava 0 */
	0xFD26, /* M -> Lava 1 */
	0xFBE3, /* N -> Lava 2 */
	0xCA00, /* O -> Lava 3 */
	0x99A0, /* P -> Lava 4 */
	0x7940, /* Q -> Lava 5 */
	0xFB21, /* R -> Lava 6 */
	0xFC85, /* S -> Lava 7 */
};

const char tiles[] =
{
	/* Air */
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"
	"AAAAAAAAAAAA"

	/* Solid */
	"JFFFFFFFFFFK"
	"IJFFFFFFFFKG"
	"IIJFFFFFFKGG"
	"IIIJFFFFKGGG"
	"IIIIJFFKGGGG"
	"IIIIIJKGGGGG"
	"IIIIIKJGGGGG"
	"IIIIKHHJGGGG"
	"IIIKHHHHJGGG"
	"IIKHHHHHHJGG"
	"IKHHHHHHHHJG"
	"KHHHHHHHHHHJ"

	/* Spike Up */
	"AAAAAFFAAAAA"
	"AAAAAFFAAAAA"
	"AAAAFFFFAAAA"
	"AAAAFFFFAAAA"
	"AAAFFFFFFAAA"
	"AAAFFFFFFAAA"
	"AAFFFFFFFFAA"
	"AAFFFFFFFFAA"
	"AFFFFFFFFFFA"
	"AFFFFFFFFFFA"
	"FFFFFFFFFFFF"
	"FFFFFFFFFFFF"

	/* Spike Down */
	"FFFFFFFFFFFF"
	"FFFFFFFFFFFF"
	"AFFFFFFFFFFA"
	"AFFFFFFFFFFA"
	"AAFFFFFFFFAA"
	"AAFFFFFFFFAA"
	"AAAFFFFFFAAA"
	"AAAFFFFFFAAA"
	"AAAAFFFFAAAA"
	"AAAAFFFFAAAA"
	"AAAAAFFAAAAA"
	"AAAAAFFAAAAA"

	/* Lava */
	"LMNOPNMNOPOO"
	"MMNOQPROOOQN"
	"NNRPRNROQORM"
	"QOOQNNQQOPRN"
	"QPORRNQQOQRR"
	"OQRSRROQOSMN"
	"QQRNOOOPQNLM"
	"SRRNNQOOORMN"
	"MRRNLSROQQRQ"
	"QRRRSMLSPOPQ"
	"NOOOONLLRPPO"
	"LNPOOQNNRRPO"

	/* Invisible */
	"JFFFFFFFFFFJ"
	"IJFFFFFFFFJG"
	"IIJJJJJJJJGG"
	"IIJFFFFFFJGG"
	"IIJFFFFFFJGG"
	"IIJFFFFFFJGG"
	"IIJFFFFFFJGG"
	"IIJFFFFFFJGG"
	"IIJFFFFFFJGG"
	"IIJJJJJJJJGG"
	"IJHHHHHHHHJG"
	"JHHHHHHHHHHJ"

	/* Start TL */
	"AAAAAAAAAAAA"
	"AAAEEEEEEEEE"
	"AAEAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAEEEEEEEEE"
	"AEAEEEEEEEEE"

	/* Start TR */
	"AAAAAAAAAAAA"
	"EEEEEEEEEAAA"
	"AAAAAAAAAEAA"
	"AAAAAAAAAAEA"
	"AAAAAAAAAAEA"
	"AAAAAAAAAAEA"
	"AAAAAAAAAAEA"
	"AAAAEAAAAAEA"
	"AAAAEEAAAAEA"
	"AAAAEEEAAAEA"
	"EEEEEEEEAAEA"
	"EEEEEEEEEAEA"

	/* Start BL */
	"AEAEEEEEEEEE"
	"AEAEEEEEEEEE"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AEAAAAAAAAAA"
	"AAEAAAAAAAAA"
	"AAAEEEEEEEEE"
	"AAAAAAAAAAAA"

	/* Start BR */
	"EEEEEEEEEAEA"
	"EEEEEEEEAAEA"
	"AAAAEEEAAAEA"
	"AAAAEEAAAAEA"
	"AAAAEAAAAAEA"
	"AAAAAAAAAAEA"
	"AAAAAAAAAAEA"
	"AAAAAAAAAAEA"
	"AAAAAAAAAAEA"
	"AAAAAAAAAEAA"
	"EEEEEEEEEAAA"
	"AAAAAAAAAAAA"

	/* Exit TL */
	"DDDDDDDDDDDD"
	"DDDDDDAAAAAA"
	"DDDDDDAAAAAA"
	"DDDDDDAAAAAA"
	"DDDDDDAAAAAA"
	"DDDDDDAAAAAA"
	"DDDDDDAAAADD"
	"DDDDDDAADDDD"
	"DDDDDDAADDAA"
	"DDDDDDADDAAD"
	"DDDDDDADDAAD"
	"DDDDDDAAAADD"

	/* Exit TR */
	"DDDDDDDDDDDD"
	"AAAAAAAAADDD"
	"AAADDAAAADDD"
	"AADDDDAAADDD"
	"AADDDDAAADDD"
	"AAADDAAAADDD"
	"DDDDAAAAADDD"
	"DDDDDAAAADDD"
	"DDDDDDAAADDD"
	"DDDADDDDADDD"
	"DDDAAADDADDD"
	"DDAAAAAAADDD"

	/* Exit BL */
	"DDDDDDAAAADD"
	"DDDDDDAAAADD"
	"DDDDDDAAAADD"
	"DDDDDAAAAADD"
	"DDDDAADDDDDD"
	"DDDAADDDDDDD"
	"DDAAAAAAAAAA"
	"DDDDDDAAAAAA"
	"DDDDDDAAAAAA"
	"DDDDDDAAAAAA"
	"DDDDDDAAAAAA"
	"DDDDDAAAAAAA"

	/* Exit BR */
	"DDAAAAAAADDD"
	"DDDAAAAAADDD"
	"ADDAAAAAADDD"
	"ADDDAAAAADDD"
	"AADDAAAAADDD"
	"AADDDAAAADDD"
	"AAADDAAAADDD"
	"AAADDDAAADDD"
	"AAAADDAAADDD"
	"AAAAAAAAADDD"
	"AAADDDAADDDD"
	"AADDDAADDDDD"

	/* Player Right */
	"AACCCCCCCCAA"
	"ACCCCCCCCCCA"
	"CCCCCCCBBCCC"
	"CCCCCCBBABCC"
	"CCCCCCBBBBCC"
	"CCCCCCCBBCCC"
	"CCCCCCCCCCCC"
	"CCCCCCCCCCCC"
	"CCCCCCCCCCCC"
	"CCCCCCCCCCCC"
	"ACCCCCCCCCCA"
	"AACCCCCCCCAA"

	/* Player Left */
	"AACCCCCCCCAA"
	"ACCCCCCCCCCA"
	"CCCBBCCCCCCC"
	"CCBABBCCCCCC"
	"CCBBBBCCCCCC"
	"CCCBBCCCCCCC"
	"CCCCCCCCCCCC"
	"CCCCCCCCCCCC"
	"CCCCCCCCCCCC"
	"CCCCCCCCCCCC"
	"ACCCCCCCCCCA"
	"AACCCCCCCCAA"
};

typedef char check_tiles_size[
	(sizeof(tiles) == 16 * 12 * 12 + 1) ? 1 : -1];
