#ifndef __STYLES_H__
#define __STYLES_H__

#define NORMAL                TERMINAL_COLOR(TERMINAL_WHITE, TERMINAL_BLACK)
#define CURSOR                TERMINAL_COLOR(TERMINAL_BLACK, TERMINAL_WHITE)
#define SELECTED              TERMINAL_COLOR(TERMINAL_BLACK, TERMINAL_YELLOW)

#endif /* __STYLES_H__ */